name: Build ChillFrames
on:
  push:
    branches:
      - master
      
env:
  SOLUTION_NAME: ChillFrames
  INTERNAL_NAME: ChillFrames
  RELEASE_DIR: ChillFrames\bin\Release\ChillFrames
  PERSONAL_PLUGIN_REPO: Gigahightier/MyDalamudPlugins
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goats.dev/ffxiv/tools/launcher/addons/Hooks/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\"
      - name: Build
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build --configuration Release
        env: 
          DOTNET_CLI_TELEMETRY_OPTOUT: true      
      - name: Archive
        run: Compress-Archive -Path ChillFrames/bin/Release/ChillFrames/* -DestinationPath ChillFrames.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: |
            ./ChillFrames/bin/Release/ChillFrames/*
